/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fbf9fa",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#a88c69",
        "primary": "#041627",
        "error": "#ba1a1a",
        "tertiary-container": "#38260b",
        "on-secondary-fixed-variant": "#464746",
        "surface-variant": "#e4e2e3",
        "inverse-on-surface": "#f2f0f2",
        "on-error-container": "#93000a",
        "status-draft": "#E5E7EB",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary": "#211200",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "inverse-primary": "#b7c8de",
        "surface-container-low": "#f5f3f4",
        "background": "#fbf9fa",
        "primary-fixed": "#d2e4fb",
        "secondary-fixed-dim": "#c7c6c5",
        "secondary-fixed": "#e3e2e1",
        "tertiary-fixed-dim": "#e1c29b",
        "status-filed": "#D1FAE5",
        "on-tertiary-fixed": "#281802",
        "on-surface": "#1b1c1d",
        "secondary-container": "#e0dfdf",
        "outline-variant": "#c4c6cd",
        "surface-container-high": "#e9e7e9",
        "on-primary-container": "#8192a7",
        "on-tertiary-fixed-variant": "#584326",
        "surface-tint": "#4f6073",
        "parchment-mid": "#F8F6F2",
        "parchment-deep": "#F2EFE9",
        "tertiary-fixed": "#feddb5",
        "on-surface-variant": "#44474c",
        "surface-container": "#efedef",
        "on-primary-fixed-variant": "#38485a",
        "surface-bright": "#fbf9fa",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0b1d2d",
        "secondary": "#5e5e5e",
        "status-flagged": "#FEE2E2",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dbd9db",
        "primary-fixed-dim": "#b7c8de",
        "outline": "#74777d",
        "inverse-surface": "#303032",
        "on-background": "#1b1c1d",
        "status-reviewed": "#DBEAFE",
        "on-secondary-container": "#626362",
        "primary-container": "#1a2b3c",
        "surface-container-highest": "#e4e2e3",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        unit: "4px",
        "rule-thin": "1px",
        margin: "32px",
        gutter: "24px",
        "rule-heavy": "2px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Bodoni Moda", "serif"],
        "citation": ["JetBrains Mono", "monospace"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Bodoni Moda", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Bodoni Moda", "serif"],
        "headline-md": ["Bodoni Moda", "serif"],
        "label-sm": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "citation": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-sm": ["13px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
